// <auto-generated>
// Template QuestPDF generado por el Diseñador Visual.
// Diseño: REAL v1.0
// </auto-generated>
#nullable enable
using System;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Services.PdfGenerator.Domain.Models;
using QuestPDF.Companion;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using SkiaSharp;
using ZXing;
using ZXing.SkiaSharp;

namespace Services.PdfGenerator.Infrastructure.Templates._900111222;

public class FacturaUbl : IInvoiceTemplate
{
    private static bool _encodingProviderRegistered;
    private static readonly object _lock = new object();

    static FacturaUbl()
    {
        RegisterEncodingProvider();
    }

    public byte[] GeneratePdf(InvoiceModel model)
    {
        if (model == null) throw new ArgumentNullException(nameof(model));
        return Document.Create(container => Compose(container, model)).GeneratePdf();
    }

    public void PreviewOnQuestPDFCompanion(InvoiceModel model)
    {
        if (model == null) throw new ArgumentNullException(nameof(model));
        Document.Create(container => Compose(container, model)).ShowInCompanion();
    }

    private void Compose(IDocumentContainer container, InvoiceModel model)
    {
        container.Page(page =>
        {
            page.Size(PageSizes.Letter.Portrait());
            page.MarginTop(20f);
            page.MarginRight(20f);
            page.MarginBottom(20f);
            page.MarginLeft(20f);
            page.DefaultTextStyle(x => x.FontSize(10f).FontFamily("Liberation Sans").FontColor("#000000"));

            page.Header().Column(col => ComposeHeader(col, model));
            page.Content().Column(content => ComposeContent(content, model));
            page.Footer().Column(col => ComposeFooter(col, model));
        });
    }

    private void ComposeHeader(ColumnDescriptor col, InvoiceModel model)
    {
        col.Item().ShowOnce().Column(c =>
        {
            c.Item().Height(80f).Layers(layers =>
            {
                layers.PrimaryLayer();
                layers.Layer()
                    .TranslateX(220f, Unit.Point).TranslateY(10f, Unit.Point)
                    .Width(160f).MinHeight(18f)
                    .Element(cell =>
                    {
                        cell.Text(Format(model.Issuer.Address, "text")).FontSize(10f).FontColor("#000000");
                    });
                layers.Layer()
                    .TranslateX(220f, Unit.Point).TranslateY(20f, Unit.Point)
                    .Width(160f).MinHeight(18f)
                    .Element(cell =>
                    {
                        cell.Text(Format(model.Issuer.City, "text")).FontSize(10f).FontColor("#000000");
                    });
                layers.Layer()
                    .TranslateX(220f, Unit.Point).TranslateY(0f, Unit.Point)
                    .Width(160f).MinHeight(18f)
                    .Element(cell =>
                    {
                        cell.Text(Format(model.Issuer.Name, "text")).FontSize(10f).FontColor("#000000");
                    });
            });
        });
        col.Item().Height(60f).Layers(layers =>
        {
            layers.PrimaryLayer();
        });
    }

    private void ComposeContent(ColumnDescriptor content, InvoiceModel model)
    {
        foreach (var grp in model.Lines.GroupBy(line => ""))
        {
            content.Item().Height(30f).Layers(layers =>
            {
                layers.PrimaryLayer();
            });
            foreach (var line in grp)
            {
                content.Item().Height(20f).Layers(layers =>
                {
                    layers.PrimaryLayer();
                    layers.Layer()
                        .TranslateX(-0f, Unit.Point).TranslateY(-0f, Unit.Point)
                        .Width(230f).MinHeight(20f)
                        .Element(cell =>
                        {
                            cell.Text(Format(line.Description, "text")).FontSize(10f).FontColor("#000000");
                        });
                    layers.Layer()
                        .TranslateX(220f, Unit.Point).TranslateY(0f, Unit.Point)
                        .Width(160f).MinHeight(18f)
                        .Element(cell =>
                        {
                            cell.Text(Format(line.LineNumber, "text")).FontSize(10f).FontColor("#000000");
                        });
                    layers.Layer()
                        .TranslateX(230f, Unit.Point).TranslateY(0f, Unit.Point)
                        .Width(160f).MinHeight(18f)
                        .Element(cell =>
                        {
                            cell.Text(Format(line.Quantity, "text")).FontSize(10f).FontColor("#000000");
                        });
                });
            }
            content.Item().Height(24f).Layers(layers =>
            {
                layers.PrimaryLayer();
            });
        }
        content.Item().Height(64f).Layers(layers =>
        {
            layers.PrimaryLayer();
        });
    }

    private void ComposeFooter(ColumnDescriptor col, InvoiceModel model)
    {
        col.Item().Height(30f).Layers(layers =>
        {
            layers.PrimaryLayer();
        });
    }

    public TemplateMetadata GetMetadata()
    {
        return new TemplateMetadata
        {
            Nit = "900111222",
            TemplateName = "REAL",
            ClientName = "Designer",
            Version = "1.0",
            LastUpdated = DateTime.UtcNow
        };
    }

    public InvoiceModel MapToCustomDto(InvoiceModel baseModel) => baseModel;

// ── Helpers ─────────────────────────────────────────────
private static void RegisterEncodingProvider()
{
    if (_encodingProviderRegistered) return;
    lock (_lock)
    {
        if (_encodingProviderRegistered) return;
        try
        {
            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
            _encodingProviderRegistered = true;
        }
        catch
        {
            _encodingProviderRegistered = false;
        }
    }
}

private static string SafeGetValue(string? value) => value ?? string.Empty;

private static string GetCustomField(InvoiceModel model, string key, string defaultValue = "")
    => model.Additional?.CustomFields?.TryGetValue(key, out var value) == true && !string.IsNullOrEmpty(value)
        ? value
        : defaultValue;

private static string LetterAmount(InvoiceModel model)
{
    var letters = PDF_Utils.NumeroALetrasCOP(model.Document?.Total_am ?? 0m);
    return string.IsNullOrWhiteSpace(letters)
        ? model.Document?.TotalLetras ?? string.Empty
        : letters;
}

private static bool Bool(string? value)
    => value != null && (value.Equals("1", StringComparison.OrdinalIgnoreCase)
        || value.Equals("true", StringComparison.OrdinalIgnoreCase)
        || value.Equals("si", StringComparison.OrdinalIgnoreCase)
        || value.Equals("s", StringComparison.OrdinalIgnoreCase));

private static string Format(object? value, string? format)
{
    if (value == null) return string.Empty;
    var text = value switch
    {
        DateTime dt => dt.ToString("dd/MM/yyyy", CultureInfo.InvariantCulture),
        decimal dec => dec.ToString(CultureInfo.InvariantCulture),
        double dbl => dbl.ToString(CultureInfo.InvariantCulture),
        IFormattable f => f.ToString(null, CultureInfo.InvariantCulture),
        _ => value.ToString() ?? string.Empty
    };
    if (string.IsNullOrWhiteSpace(format) || format == "text") return text;

    var culture = CultureInfo.GetCultureInfo("es-CO");
    if (format.StartsWith("date:", StringComparison.OrdinalIgnoreCase))
    {
        return DateTime.TryParse(text, CultureInfo.InvariantCulture, DateTimeStyles.None, out var date)
            ? date.ToString(format[5..], culture)
            : text;
    }

    decimal? num = decimal.TryParse(text.Replace("$", "").Replace(",", "").Trim(), NumberStyles.Any, CultureInfo.InvariantCulture, out var n)
        ? n : null;

    return format switch
    {
        "currency" => num?.ToString("C0", culture) ?? text,
        "currency2" => num?.ToString("C2", culture) ?? text,
        "number" => num?.ToString("N0", culture) ?? text,
        "number2" => num?.ToString("N2", culture) ?? text,
        "upper" => text.ToUpperInvariant(),
        "lower" => text.ToLowerInvariant(),
        _ => text
    };
}

private static byte[]? SafeLoadImage(string? source)
{
    if (string.IsNullOrWhiteSpace(source)) return null;
    try
    {
        if (source.StartsWith("data:", StringComparison.OrdinalIgnoreCase))
        {
            var idx = source.IndexOf("base64,", StringComparison.OrdinalIgnoreCase);
            if (idx >= 0) return Convert.FromBase64String(source[(idx + 7)..]);
        }
        if (File.Exists(source)) return File.ReadAllBytes(source);
        return Convert.FromBase64String(source);
    }
    catch
    {
        return null;
    }
}private static void Canvas(IContainer container, Action<SKCanvas, QuestPDF.Infrastructure.Size> draw)
{
    container.Svg(size =>
    {
        using var stream = new MemoryStream();
        using (var canvas = SKSvgCanvas.Create(new SKRect(0, 0, size.Width, size.Height), stream))
            draw(canvas, size);
        return System.Text.Encoding.UTF8.GetString(stream.ToArray());
    });
}

private static void DrawShape(IContainer cell, string shape, float radius, float pt, float pr, float pb, float pl, string? fill, string? border, float borderWidth)
{
    var box = cell;
    if (pt > 0) box = box.PaddingTop(pt);
    if (pr > 0) box = box.PaddingRight(pr);
    if (pb > 0) box = box.PaddingBottom(pb);
    if (pl > 0) box = box.PaddingLeft(pl);

    if (shape == "rectangle")
    {
        if (fill != null) box = box.Background(fill);
        if (!string.IsNullOrWhiteSpace(border) && borderWidth > 0) box = box.Border(borderWidth).BorderColor(border);
        return;
    }

    var fillColor = string.IsNullOrWhiteSpace(fill) ? SKColors.Transparent : SKColor.Parse(fill);
    var borderColor = string.IsNullOrWhiteSpace(border) ? SKColors.Black : SKColor.Parse(border);
    var ellipse = shape == "ellipse";

    Canvas(box, (canvas, size) =>
    {
        var rect = new SKRect(0, 0, size.Width, size.Height);
        using (var paint = new SKPaint
               {
                   IsAntialias = true,
                   Style = fill != null ? SKPaintStyle.Fill : SKPaintStyle.Stroke,
                   Color = fill != null ? fillColor : borderColor,
                   StrokeWidth = borderWidth
               })
        {
            if (ellipse) canvas.DrawOval(rect, paint);
            else canvas.DrawRoundRect(rect, radius, radius, paint);
        }

        if (fill != null && border != null)
        {
            using var stroke = new SKPaint
            {
                IsAntialias = true,
                Style = SKPaintStyle.Stroke,
                Color = borderColor,
                StrokeWidth = borderWidth
            };
            if (ellipse) canvas.DrawOval(rect, stroke);
            else canvas.DrawRoundRect(rect, radius, radius, stroke);
        }
    });
}

private static void DrawBarcode(IContainer cell, string? value, string symbology, float height)
{
    if (string.IsNullOrWhiteSpace(value))
    {
        cell.Text("");
        return;
    }

    var format = symbology.ToUpperInvariant() switch
    {
        "QR" or "QRCODE" => BarcodeFormat.QR_CODE,
        "CODE_39" => BarcodeFormat.CODE_39,
        "EAN_13" => BarcodeFormat.EAN_13,
        _ => BarcodeFormat.CODE_128
    };

    var writer = new BarcodeWriter
    {
        Format = format,
        Options = new() { Height = (int)(height * 3), Width = 600, PureBarcode = format != BarcodeFormat.QR_CODE, Margin = 0 }
    };

    using var bitmap = writer.Write(value);
    using var png = bitmap.Encode(SKEncodedImageFormat.Png, 100);
    if (png == null)
    {
        cell.Text("");
        return;
    }

    cell.Image(png.ToArray()).FitArea();
}

private static void DrawCheckBox(IContainer cell, bool isChecked, string? text, string? color, float fontSize)
{
    var col = string.IsNullOrWhiteSpace(color) ? SKColors.Black : SKColor.Parse(color);
    var glyph = Math.Max(fontSize + 3, 13f);

    cell.Row(row =>
    {
        Canvas(row.ConstantItem(glyph + 3), (canvas, size) =>
        {
            var s = Math.Min(size.Width, size.Height) - 2;
            if (s <= 0) return;

            var rect = new SKRect(
                (size.Width - s) / 2,
                (size.Height - s) / 2,
                (size.Width + s) / 2,
                (size.Height + s) / 2);

            using var borderPaint = new SKPaint
            {
                IsAntialias = true,
                Style = SKPaintStyle.Stroke,
                Color = col,
                StrokeWidth = 1.2f
            };
            canvas.DrawRoundRect(rect, 2f, 2f, borderPaint);

            if (isChecked)
            {
                using var checkPaint = new SKPaint
                {
                    IsAntialias = true,
                    Style = SKPaintStyle.Stroke,
                    Color = col,
                    StrokeWidth = 1.8f,
                    StrokeCap = SKStrokeCap.Round,
                    StrokeJoin = SKStrokeJoin.Round
                };
                var p1 = new SKPoint(rect.Left + rect.Width * 0.22f, rect.Top + rect.Height * 0.5f);
                var p2 = new SKPoint(rect.Left + rect.Width * 0.42f, rect.Top + rect.Height * 0.72f);
                var p3 = new SKPoint(rect.Left + rect.Width * 0.78f, rect.Top + rect.Height * 0.28f);
                canvas.DrawLine(p1, p2, checkPaint);
                canvas.DrawLine(p2, p3, checkPaint);
            }
        });

        row.RelativeItem().Text(text ?? "").FontSize(fontSize).FontColor(string.IsNullOrWhiteSpace(color) ? "#000000" : color);
    });
}
}
