// <auto-generated>
// Template QuestPDF generado por el Diseñador Visual.
// Diseño: EXPORTACIONES SAS v1.0
// </auto-generated>
#nullable enable
using System;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Text;
using Services.PdfGenerator.Domain.Models;
using QuestPDF.Companion;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using QRCoder;
using ZXing;

namespace Services.PdfGenerator.Infrastructure.Templates._900111222;

public class FacturaUbl : IInvoiceTemplate
{
    private static bool _encodingProviderRegistered;
    private static readonly object _lock = new object();

    static FacturaUbl()
    {
        RegisterEncodingProvider();
    }

    public byte[] GeneratePdf(InvoiceModel model)
    {
        if (model == null) throw new ArgumentNullException(nameof(model));
        return Document.Create(container => Compose(container, model)).GeneratePdf();
    }

    public void PreviewOnQuestPDFCompanion(InvoiceModel model)
    {
        if (model == null) throw new ArgumentNullException(nameof(model));
        Document.Create(container => Compose(container, model)).ShowInCompanion();
    }

    private void Compose(IDocumentContainer container, InvoiceModel model)
    {
        container.Page(page =>
        {
            page.Size(PageSizes.Letter.Portrait());
            page.MarginTop(20f);
            page.MarginRight(20f);
            page.MarginBottom(20f);
            page.MarginLeft(20f);
            page.DefaultTextStyle(x => x.FontSize(10f).FontFamily("Liberation Sans").FontColor("#000000"));

            page.Header().Column(col => ComposeHeader(col, model));
            page.Content().Column(content => ComposeContent(content, model));
            page.Footer().Column(col => ComposeFooter(col, model));
        });
    }

    private void ComposeHeader(ColumnDescriptor col, InvoiceModel model)
    {
        col.Item().ShowOnce().Column(c =>
        {
            c.Item().Height(8f).Layers(layers =>
            {
                layers.PrimaryLayer();
            });
        });
        col.Item().Height(70f).Layers(layers =>
        {
            layers.PrimaryLayer();
            layers.Layer()
                .TranslateX(240f, Unit.Point).TranslateY(0f, Unit.Point)
                .Width(160f).MinHeight(18f)
                .Element(cell =>
                {
                    cell.AlignCenter().Text(Format(model.Issuer.Name, "text")).FontSize(10f).FontColor("#000000");
                });
            layers.Layer()
                .TranslateX(240f, Unit.Point).TranslateY(10f, Unit.Point)
                .Width(160f).MinHeight(18f)
                .Element(cell =>
                {
                    cell.AlignCenter().Text(Format(model.Issuer.Email, "text")).FontSize(10f).FontColor("#000000");
                });
            layers.Layer()
                .TranslateX(240f, Unit.Point).TranslateY(20f, Unit.Point)
                .Width(160f).MinHeight(18f)
                .Element(cell =>
                {
                    cell.AlignCenter().Text(Format(model.Issuer.City, "text")).FontSize(10f).FontColor("#000000");
                });
        });
    }

    private void ComposeContent(ColumnDescriptor content, InvoiceModel model)
    {
        foreach (var grp in model.Lines.GroupBy(line => ""))
        {
            content.Item().Height(70f).Layers(layers =>
            {
                layers.PrimaryLayer();
                layers.Layer()
                    .TranslateX(0f, Unit.Point).TranslateY(0f, Unit.Point)
                    .Width(570f).MinHeight(60f)
                    .Element(cell =>
                    {
                        DrawShape(cell, "rectangle", 6f, 0f, 0f, 0f, 0f, "#FFFFFF", "#000000", 0.5f);
                    });
                layers.Layer()
                    .TranslateX(0f, Unit.Point).TranslateY(0f, Unit.Point)
                    .Width(120f).MinHeight(18f)
                    .Element(cell =>
                    {
                        cell.Text("NOMBRE CONTACTO").FontSize(10f).FontColor("#000000");
                    });
                layers.Layer()
                    .TranslateX(0f, Unit.Point).TranslateY(20f, Unit.Point)
                    .Width(120f).MinHeight(20f)
                    .Element(cell =>
                    {
                        cell.Text("TELEFONO CONTACTO").FontSize(10f).FontColor("#000000");
                    });
                layers.Layer()
                    .TranslateX(0f, Unit.Point).TranslateY(40f, Unit.Point)
                    .Width(120f).MinHeight(18f)
                    .Element(cell =>
                    {
                        cell.Text("DIRECCION CONTACTO").FontSize(10f).FontColor("#000000");
                    });
                layers.Layer()
                    .TranslateX(100f, Unit.Point).TranslateY(0f, Unit.Point)
                    .Width(160f).MinHeight(18f)
                    .Element(cell =>
                    {
                        cell.Text(Format(model.Customer.Name, "text")).FontSize(10f).FontColor("#000000");
                    });
                layers.Layer()
                    .TranslateX(110f, Unit.Point).TranslateY(40f, Unit.Point)
                    .Width(160f).MinHeight(18f)
                    .Element(cell =>
                    {
                        cell.Text(Format(model.Customer.Address, "text")).FontSize(10f).FontColor("#000000");
                    });
                layers.Layer()
                    .TranslateX(110f, Unit.Point).TranslateY(20f, Unit.Point)
                    .Width(160f).MinHeight(18f)
                    .Element(cell =>
                    {
                        cell.Text(Format(model.InformacionAdditional.Telefono_Receptor, "text")).FontSize(10f).FontColor("#000000");
                    });
                layers.Layer()
                    .TranslateX(280f, Unit.Point).TranslateY(0f, Unit.Point)
                    .Width(40f).MinHeight(60f)
                    .Element(cell =>
                    {
                        cell.AlignCenter().Width(1f).Background("#000000");
                    });
            });
            content.Item().Height(20f).Layers(layers =>
            {
                layers.PrimaryLayer();
            });
            foreach (var line in grp)
            {
                content.Item().Height(20f).Layers(layers =>
                {
                    layers.PrimaryLayer();
                    layers.Layer()
                        .TranslateX(-0f, Unit.Point).TranslateY(0f, Unit.Point)
                        .Width(30f).MinHeight(20f)
                        .Element(cell =>
                        {
                            cell.AlignMiddle().AlignCenter().Text(Format(line.LineNumber, "text")).FontSize(10f).FontColor("#000000");
                        });
                    layers.Layer()
                        .TranslateX(30f, Unit.Point).TranslateY(0f, Unit.Point)
                        .Width(240f).MinHeight(20f)
                        .Element(cell =>
                        {
                            cell.Text(Format(line.Description, "text")).FontSize(10f).FontColor("#000000");
                        });
                    layers.Layer()
                        .TranslateX(280f, Unit.Point).TranslateY(-0f, Unit.Point)
                        .Width(20f).MinHeight(20f)
                        .Element(cell =>
                        {
                            cell.AlignMiddle().AlignCenter().Text(Format(line.Quantity, "text")).FontSize(10f).FontColor("#000000");
                        });
                });
            }
            content.Item().Height(10f).Layers(layers =>
            {
                layers.PrimaryLayer();
            });
        }
        content.Item().Height(60f).Layers(layers =>
        {
            layers.PrimaryLayer();
        });
    }

    private void ComposeFooter(ColumnDescriptor col, InvoiceModel model)
    {
        col.Item().Height(80f).Layers(layers =>
        {
            layers.PrimaryLayer();
            layers.Layer()
                .TranslateX(-0f, Unit.Point).TranslateY(0f, Unit.Point)
                .Width(420f).MinHeight(20f)
                .Element(cell =>
                {
                    cell.Text(Format(model.Additional.Notes, "text")).FontSize(10f).FontColor("#000000");
                });
            layers.Layer()
                .TranslateX(-0f, Unit.Point).TranslateY(20f, Unit.Point)
                .Width(570f).MinHeight(30f)
                .Element(cell =>
                {
                    cell.Text(Format(GetCustomField(model, "ResolucionTexto"), "text")).FontSize(10f).FontColor("#000000");
                });
        });
    }

    public TemplateMetadata GetMetadata()
    {
        return new TemplateMetadata
        {
            Nit = "900111222",
            TemplateName = "EXPORTACIONES SAS",
            ClientName = "Designer",
            Version = "1.0",
            LastUpdated = DateTime.UtcNow
        };
    }

    public InvoiceModel MapToCustomDto(InvoiceModel baseModel) => baseModel;

// ── Helpers ─────────────────────────────────────────────
private static void RegisterEncodingProvider()
{
    if (_encodingProviderRegistered) return;
    lock (_lock)
    {
        if (_encodingProviderRegistered) return;
        try
        {
            Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
            _encodingProviderRegistered = true;
        }
        catch
        {
            _encodingProviderRegistered = false;
        }
    }
}

private static string SafeGetValue(string? value) => value ?? string.Empty;

private static string GetCustomField(InvoiceModel model, string key, string defaultValue = "")
    => model.Additional?.CustomFields?.TryGetValue(key, out var value) == true && !string.IsNullOrEmpty(value)
        ? value
        : defaultValue;

private static string LetterAmount(InvoiceModel model)
{
    var letters = PDF_Utils.NumeroALetrasCOP(model.Document?.Total_am ?? 0m);
    return string.IsNullOrWhiteSpace(letters)
        ? model.Document?.TotalLetras ?? string.Empty
        : letters;
}

private static bool Bool(string? value)
    => value != null && (value.Equals("1", StringComparison.OrdinalIgnoreCase)
        || value.Equals("true", StringComparison.OrdinalIgnoreCase)
        || value.Equals("si", StringComparison.OrdinalIgnoreCase)
        || value.Equals("s", StringComparison.OrdinalIgnoreCase));

private static string Format(object? value, string? format)
{
    if (value == null) return string.Empty;
    var text = value switch
    {
        DateTime dt => dt.ToString("dd/MM/yyyy", CultureInfo.InvariantCulture),
        decimal dec => dec.ToString(CultureInfo.InvariantCulture),
        double dbl => dbl.ToString(CultureInfo.InvariantCulture),
        IFormattable f => f.ToString(null, CultureInfo.InvariantCulture),
        _ => value.ToString() ?? string.Empty
    };
    if (string.IsNullOrWhiteSpace(format) || format == "text") return text;

    var culture = CultureInfo.GetCultureInfo("es-CO");
    if (format.StartsWith("date:", StringComparison.OrdinalIgnoreCase))
    {
        return DateTime.TryParse(text, CultureInfo.InvariantCulture, DateTimeStyles.None, out var date)
            ? date.ToString(format[5..], culture)
            : text;
    }

    decimal? num = decimal.TryParse(text.Replace("$", "").Replace(",", "").Trim(), NumberStyles.Any, CultureInfo.InvariantCulture, out var n)
        ? n : null;

    return format switch
    {
        "currency" => num?.ToString("C0", culture) ?? text,
        "currency2" => num?.ToString("C2", culture) ?? text,
        "number" => num?.ToString("N0", culture) ?? text,
        "number2" => num?.ToString("N2", culture) ?? text,
        "upper" => text.ToUpperInvariant(),
        "lower" => text.ToLowerInvariant(),
        _ => text
    };
}

private static byte[]? SafeLoadImage(string? source)
{
    if (string.IsNullOrWhiteSpace(source)) return null;
    try
    {
        if (source.StartsWith("data:", StringComparison.OrdinalIgnoreCase))
        {
            var idx = source.IndexOf("base64,", StringComparison.OrdinalIgnoreCase);
            if (idx >= 0) return Convert.FromBase64String(source[(idx + 7)..]);
        }
        if (File.Exists(source)) return File.ReadAllBytes(source);
        return Convert.FromBase64String(source);
    }
    catch
    {
        return null;
    }
}private static byte[]? SafeGenerateQRCode(string qrUrl)
{
    if (string.IsNullOrWhiteSpace(qrUrl))
        return null;

    try
    {
        using var qrGenerator = new QRCodeGenerator();
        using var qrCodeData = qrGenerator.CreateQrCode(qrUrl, QRCodeGenerator.ECCLevel.L);
        using var qrCode = new PngByteQRCode(qrCodeData);
        return qrCode.GetGraphic(8);
    }
    catch (Exception)
    {
        // Si falla generación de QR, continuar sin QR.
        return null;
    }
}

private static void DrawShape(IContainer cell, string shape, float radius, float pt, float pr, float pb, float pl, string? fill, string? border, float borderWidth)
{
    var box = cell;
    if (pt > 0) box = box.PaddingTop(pt);
    if (pr > 0) box = box.PaddingRight(pr);
    if (pb > 0) box = box.PaddingBottom(pb);
    if (pl > 0) box = box.PaddingLeft(pl);

    if (shape == "rectangle")
    {
        if (fill != null) box = box.Background(fill);
        if (!string.IsNullOrWhiteSpace(border) && borderWidth > 0) box = box.Border(borderWidth).BorderColor(border);
        return;
    }

    // TODO: elipse sin canvas de bajo nivel; se aproxima con relleno/borde.
    if (fill != null) box = box.Background(fill);
    if (!string.IsNullOrWhiteSpace(border) && borderWidth > 0) box = box.Border(borderWidth).BorderColor(border);
}

private static void DrawBarcode(IContainer cell, string? value, string symbology, float height)
{
    if (string.IsNullOrWhiteSpace(value))
    {
        cell.Text("");
        return;
    }

    var isQr = string.Equals(symbology, "QR", StringComparison.OrdinalIgnoreCase)
               || string.Equals(symbology, "QRCODE", StringComparison.OrdinalIgnoreCase);
    if (!isQr)
    {
        // Solo se renderiza QR (como el template manual). Otros symbologies se muestran como texto.
        cell.Text(value).FontSize(Math.Max(height - 4, 7f));
        return;
    }

    var bytes = SafeGenerateQRCode(value);
    if (bytes == null)
    {
        cell.Text("");
        return;
    }

    cell.Image(bytes).FitArea();
}

private static void DrawCheckBox(IContainer cell, bool isChecked, string? text, string? color, float fontSize)
{
    var col = string.IsNullOrWhiteSpace(color) ? "#000000" : color;
    var glyph = isChecked ? "☑" : "☐";

    cell.Row(row =>
    {
        row.ConstantItem(fontSize + 4).Text(glyph).FontSize(fontSize).FontColor(col);
        row.RelativeItem().Text(text ?? "").FontSize(fontSize).FontColor(col);
    });
}
}

// Paleta de colores corporativa AJE
static class BrandColors
{
    public static string AjeGreen = "#00B4A5"; // Verde agua AJE
    public static string TableHeaderBg = "#E6F7F5"; // Verde menta claro
    public static string BorderGray = "#CCCCCC"; // Gris medio para bordes
    public static string BorderDark = "#666666"; // Gris oscuro
    public static string TextBlack = "#000000"; // Negro sólido
}

// Estilos específicos para la tabla de items
static class InvoiceTableStyles
{
    public static string HeaderBackground = "#E6F7F5";
    public static string CellBackground = "#FFFFFF";
    public static string BorderColor = "#000000";
    public static string TextColor = "#000000";

    public static float HeaderFontSize = 5.5f;
    public static float DataFontSize = 5.5f;
    public static string FontFamily = "Liberation Sans";

    public static float BorderWidth = 0.5f;

    public static float HeaderPaddingVertical = 0.9f;
    public static float HeaderPaddingHorizontal = 1.1f;
    public static float DataPaddingVertical = 0.75f;
    public static float DataPaddingHorizontal = 1.1f;
}
