using System.Globalization;
using System.Text;
using System.Text.RegularExpressions;
using PdfQuickDebug.Designer.Model;

namespace PdfQuickDebug.Designer.CodeGen;

/// <summary>
/// Genera un template QuestPDF real (IInvoiceTemplate) a partir del árbol
/// compositivo del diseño. Mapeo 1:1 de <see cref="LayoutNode"/> a la API
/// fluida de QuestPDF (Column/Row/Table/Container/…), idéntico al renderer.
/// </summary>
public static class DesignToCSharpGenerator
{
    public static string Generate(ReportDesign design, BindingMap? map = null, string? className = null, string? ns = null)
    {
        map ??= BindingMap.CreateDefault();
        className ??= GenerateClassName(design);
        ns ??= "PdfQuickDebug.Templates";
        var isLocal = ns == "PdfQuickDebug.Templates";
        var defFont = design.Page.DefaultFontSize;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// Template QuestPDF generado por el Diseñador Visual.");
        sb.AppendLine($"// Diseño: {design.Metadata.TemplateName} v{design.Metadata.Version}");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine("#nullable enable");
        if (isLocal)
        {
            sb.AppendLine("using System.Globalization;");
            sb.AppendLine("using System.Text;");
            sb.AppendLine("using PdfQuickDebug.Core;");
            sb.AppendLine("using QRCoder;");
            sb.AppendLine("using QuestPDF.Companion;");
            sb.AppendLine("using QuestPDF.Fluent;");
            sb.AppendLine("using QuestPDF.Helpers;");
            sb.AppendLine("using QuestPDF.Infrastructure;");
        }
        else
        {
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Globalization;");
            sb.AppendLine("using System.IO;");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("using System.Text;");
            sb.AppendLine("using PdfQuickDebug.Core;");
            sb.AppendLine("using QuestPDF.Companion;");
            sb.AppendLine("using QuestPDF.Fluent;");
            sb.AppendLine("using QuestPDF.Helpers;");
            sb.AppendLine("using QuestPDF.Infrastructure;");
            sb.AppendLine("using QRCoder;");
        }
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine($"public class {className} : IInvoiceTemplate");
        sb.AppendLine("{");
        sb.AppendLine("    private static bool _encodingProviderRegistered;");
        sb.AppendLine("    private static readonly object _lock = new object();");
        sb.AppendLine();
        sb.AppendLine($"    static {className}()");
        sb.AppendLine("    {");
        sb.AppendLine("        RegisterEncodingProvider();");
        sb.AppendLine("    }");
        sb.AppendLine();

        EmitGeneratePdf(sb, design, map, defFont);
        sb.AppendLine();
        EmitComposeMethods(sb, design, map, defFont);
        sb.AppendLine();
        EmitMetadata(sb, design);
        sb.AppendLine();
        sb.AppendLine("    public InvoiceModel MapToCustomDto(InvoiceModel baseModel) => baseModel;");
        sb.AppendLine();
        sb.AppendLine(CommonHelpers);
        sb.AppendLine();
        sb.AppendLine(LocalQrHelpers);
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string GenerateClassName(ReportDesign design) => Sanitize(design.Metadata.TemplateName);

    /* ── Estructura del template ───────────────────────────── */

    private static void EmitGeneratePdf(StringBuilder sb, ReportDesign design, BindingMap map, float defFont)
    {
        sb.AppendLine("    public byte[] GeneratePdf(InvoiceModel model)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (model == null) throw new ArgumentNullException(nameof(model));");
        sb.AppendLine("        return Document.Create(container => Compose(container, model)).GeneratePdf();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    public void PreviewOnQuestPDFCompanion(InvoiceModel model)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (model == null) throw new ArgumentNullException(nameof(model));");
        sb.AppendLine("        Document.Create(container => Compose(container, model)).ShowInCompanion();");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    private void Compose(IDocumentContainer container, InvoiceModel model)");
        sb.AppendLine("    {");
        sb.AppendLine("        container.Page(page =>");
        sb.AppendLine("        {");
        EmitPage(sb, design);
        sb.AppendLine($"            page.DefaultTextStyle(x => x.FontSize({F(defFont)}f).FontFamily(\"{Escape(design.Page.FontFamily)}\").FontColor(\"#000000\"));");
        sb.AppendLine();
        if (design.Header.Children.Count > 0)
            sb.AppendLine("            page.Header().Column(col => ComposeHeader(col, model));");
        sb.AppendLine("            page.Content().Column(content => ComposeContent(content, model));");
        if (design.Footer.Children.Count > 0)
            sb.AppendLine("            page.Footer().Column(col => ComposeFooter(col, model));");
        sb.AppendLine("        });");
        sb.AppendLine("    }");
    }

    private static void EmitPage(StringBuilder sb, ReportDesign design)
    {
        var p = design.Page;

        if (p.Width > 0 && p.Height > 0)
        {
            sb.AppendLine($"            page.Size({F(p.Width)}f, {F(p.Height)}f, Unit.Point);");
        }
        else
        {
            var sizeName = PageSizeCatalog.TryGet(p.Size) is null ? "Letter" : p.Size;
            var orientation = string.Equals(p.Orientation, "Landscape", StringComparison.OrdinalIgnoreCase)
                ? ".Landscape()" : ".Portrait()";
            sb.AppendLine($"            page.Size(PageSizes.{sizeName}{orientation});");
        }

        var m = p.Margins ?? new MarginDesign();
        sb.AppendLine($"            page.MarginTop({F(m.Top)}f);");
        sb.AppendLine($"            page.MarginRight({F(m.Right)}f);");
        sb.AppendLine($"            page.MarginBottom({F(m.Bottom)}f);");
        sb.AppendLine($"            page.MarginLeft({F(m.Left)}f);");
    }

    private static void EmitComposeMethods(StringBuilder sb, ReportDesign design, BindingMap map, float defFont)
    {
        sb.AppendLine("    private void ComposeHeader(ColumnDescriptor col, InvoiceModel model)");
        sb.AppendLine("    {");
        foreach (var child in design.Header.Children)
            EmitNode(sb, child, "        ", "col.Item()", false, defFont, map);
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    private void ComposeContent(ColumnDescriptor content, InvoiceModel model)");
        sb.AppendLine("    {");
        foreach (var child in design.Content.Children)
            EmitNode(sb, child, "        ", "content.Item()", false, defFont, map);
        sb.AppendLine("    }");
        sb.AppendLine();

        sb.AppendLine("    private void ComposeFooter(ColumnDescriptor col, InvoiceModel model)");
        sb.AppendLine("    {");
        foreach (var child in design.Footer.Children)
            EmitNode(sb, child, "        ", "col.Item()", false, defFont, map);
        sb.AppendLine("    }");
    }

    /* ── Emisión de nodos ──────────────────────────────────── */

    private static void EmitNode(StringBuilder sb, LayoutNode node, string indent, string target, bool inDetail, float defFont, BindingMap map)
    {
        if (!node.Visible) return;

        switch (node.Type)
        {
            case "column":
                sb.AppendLine($"{indent}{target}.Column(col =>");
                sb.AppendLine($"{indent}{{");
                foreach (var child in node.Children)
                    EmitNode(sb, child, indent + "    ", "col.Item()", inDetail, defFont, map);
                sb.AppendLine($"{indent}}});");
                break;

            case "row":
                sb.AppendLine($"{indent}{target}.Row(row =>");
                sb.AppendLine($"{indent}{{");
                foreach (var child in node.Children)
                {
                    var item = child.Width is > 0
                        ? $"row.ConstantItem({F(child.Width.Value)}f)"
                        : $"row.RelativeItem({F(child.Weight ?? 1f)}f)";
                    EmitNode(sb, child, indent + "    ", item, inDetail, defFont, map);
                }
                sb.AppendLine($"{indent}}});");
                break;

            case "container":
            {
                var chain = NodeChain(node, target);
                if (node.Height is > 0) chain += $".Height({F(node.Height.Value)}f)";
                if (node.Width is > 0) chain += $".Width({F(node.Width.Value)}f)";
                sb.AppendLine($"{indent}{chain}.Column(col =>");
                sb.AppendLine($"{indent}{{");
                foreach (var child in node.Children)
                    EmitNode(sb, child, indent + "    ", "col.Item()", inDetail, defFont, map);
                sb.AppendLine($"{indent}}});");
                break;
            }

            case "spacer":
                sb.AppendLine($"{indent}{NodeChain(node, target)}.Height({F(node.Height ?? node.SpacerHeight)}f);");
                break;

            case "pageBreak":
                sb.AppendLine($"{indent}{target}.PageBreak();");
                break;

            case "text":
                sb.AppendLine($"{indent}{NodeChain(node, target)}.Text(\"{Escape(node.Text)}\"){TextStyles(node.Style, defFont)};");
                break;

            case "field":
            {
                var expr = node.Expression != null
                    ? $"\"{Escape(node.Binding?.Default ?? string.Empty)}\" /* TODO: expresión */"
                    : ResolveExpr(node.Binding, inDetail, map);
                sb.AppendLine($"{indent}{NodeChain(node, target)}.Text(Format({expr}, \"{Escape(node.Format ?? "text")}\")){TextStyles(node.Style, defFont)};");
                break;
            }

            case "image":
            {
                var source = !string.IsNullOrWhiteSpace(node.Source)
                    ? $"\"{Escape(node.Source)}\""
                    : ResolveExpr(node.Binding, inDetail, map);
                var chain = NodeChain(node, target);
                if (node.Height is > 0) chain += $".Height({F(node.Height.Value)}f)";
                if (node.Width is > 0) chain += $".Width({F(node.Width.Value)}f)";
                sb.AppendLine($"{indent}{chain}.Image(SafeLoadImage({source})).FitArea();");
                break;
            }

            case "barcode":
            {
                var expr = ResolveExpr(node.Binding, inDetail, map);
                sb.AppendLine($"{indent}DrawBarcode({NodeChain(node, target)}, {expr}, \"{Escape(node.Symbology ?? "CODE_128")}\", {F(node.Height ?? 44f)}f);");
                break;
            }

            case "line":
            {
                var thickness = node.Thickness <= 0 ? 1f : node.Thickness;
                var color = node.Style?.Color ?? "#000000";
                var chain = NodeChain(node, target);
                if (string.Equals(node.Direction, "vertical", StringComparison.OrdinalIgnoreCase))
                    sb.AppendLine($"{indent}{chain}.AlignCenter().Width({F(thickness)}f).Background(\"{color}\");");
                else
                    sb.AppendLine($"{indent}{chain}.AlignMiddle().Height({F(thickness)}f).Background(\"{color}\");");
                break;
            }

            case "table":
                EmitTableNode(sb, node, indent, target, defFont, map);
                break;
        }
    }

    private static void EmitTableNode(StringBuilder sb, LayoutNode node, string indent, string target, float defFont, BindingMap map)
    {
        sb.AppendLine($"{indent}{NodeChain(node, target)}.Table(t =>");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    t.ColumnsDefinition(cd =>");
        sb.AppendLine($"{indent}    {{");
        foreach (var column in node.Columns)
        {
            if (column.Width is > 0)
                sb.AppendLine($"{indent}        cd.ConstantColumn({F(column.Width.Value)}f);");
            else
                sb.AppendLine($"{indent}        cd.RelativeColumn({F(column.Relative ?? 1f)}f);");
        }
        sb.AppendLine($"{indent}    }});");

        if (node.ShowHeader)
        {
            sb.AppendLine($"{indent}    t.Header(h =>");
            sb.AppendLine($"{indent}    {{");
            foreach (var column in node.Columns)
                sb.AppendLine($"{indent}        h.Cell().Element(c => {CellChain(column.Style)}.Text(\"{Escape(column.Header)}\"){TextStyles(column.Style, defFont)});");
            sb.AppendLine($"{indent}    }});");
        }

        sb.AppendLine($"{indent}    foreach (var line in model.Lines)");
        sb.AppendLine($"{indent}    {{");
        foreach (var column in node.Columns)
        {
            var expr = ResolveExpr(column.Binding, true, map);
            sb.AppendLine($"{indent}        t.Cell().Element(c => {CellChain(column.Style)}.Text(Format({expr}, \"{Escape(column.Format ?? "text")}\")){TextStyles(column.Style, defFont)});");
        }
        sb.AppendLine($"{indent}    }}");
        sb.AppendLine($"{indent}}});");
    }

    private static string CellChain(StyleDesign? style)
    {
        var c = "c.Padding(3)";
        if (!string.IsNullOrWhiteSpace(style?.Background)) c += $".Background(\"{style.Background}\")";
        if (!string.IsNullOrWhiteSpace(style?.BorderColor)) c += $".Border({F(style.BorderWidth ?? 0.5f)}f).BorderColor(\"{style.BorderColor}\")";
        if (!string.IsNullOrWhiteSpace(style?.Align))
            c += style.Align.ToLowerInvariant() switch { "center" => ".AlignCenter()", "right" => ".AlignRight()", _ => ".AlignLeft()" };
        return c;
    }

    private static string NodeChain(LayoutNode node, string baseVar)
    {
        var c = baseVar;
        var p = node.Padding;
        if (p.Top > 0) c += $".PaddingTop({F(p.Top)}f)";
        if (p.Right > 0) c += $".PaddingRight({F(p.Right)}f)";
        if (p.Bottom > 0) c += $".PaddingBottom({F(p.Bottom)}f)";
        if (p.Left > 0) c += $".PaddingLeft({F(p.Left)}f)";
        if (!string.IsNullOrWhiteSpace(node.Background)) c += $".Background(\"{node.Background}\")";
        if (!string.IsNullOrWhiteSpace(node.BorderColor)) c += $".Border({F(node.BorderWidth ?? 0.5f)}f).BorderColor(\"{node.BorderColor}\")";

        var s = node.Style;
        if (!string.IsNullOrWhiteSpace(s?.VerticalAlign))
            c += s.VerticalAlign.ToLowerInvariant() switch { "middle" => ".AlignMiddle()", "bottom" => ".AlignBottom()", _ => ".AlignTop()" };
        if (!string.IsNullOrWhiteSpace(s?.Align))
            c += s.Align.ToLowerInvariant() switch { "center" => ".AlignCenter()", "right" => ".AlignRight()", _ => ".AlignLeft()" };

        return c;
    }

    private static string TextStyles(StyleDesign? s, float def)
    {
        var t = $".FontSize({F(s?.FontSize ?? def)}f)";
        if (!string.IsNullOrWhiteSpace(s?.FontFamily)) t += $".FontFamily(\"{s.FontFamily}\")";
        if (s?.Bold == true) t += ".Bold()";
        if (s?.Italic == true) t += ".Italic()";
        if (s?.Underline == true) t += ".Underline()";
        if (s?.Strikeout == true) t += ".Strikethrough()";
        if (!string.IsNullOrWhiteSpace(s?.Color)) t += $".FontColor(\"{s.Color}\")";
        return t;
    }

    private static void EmitMetadata(StringBuilder sb, ReportDesign design)
    {
        var m = design.Metadata;
        sb.AppendLine("    public TemplateMetadata GetMetadata()");
        sb.AppendLine("    {");
        sb.AppendLine("        return new TemplateMetadata");
        sb.AppendLine("        {");
        sb.AppendLine($"            Nit = \"{Escape(m.Nit)}\",");
        sb.AppendLine($"            TemplateName = \"{Escape(m.TemplateName)}\",");
        sb.AppendLine($"            ClientName = \"{Escape(m.ClientName)}\",");
        sb.AppendLine($"            Version = \"{Escape(m.Version)}\",");
        sb.AppendLine("            LastUpdated = DateTime.UtcNow");
        sb.AppendLine("        };");
        sb.AppendLine("    }");
    }

    /* ── Resolución de bindings ────────────────────────────── */

    private static bool IsCSharpExpr(string? value)
        => !string.IsNullOrWhiteSpace(value)
           && (Regex.IsMatch(value, @"^\s*line\.", RegexOptions.IgnoreCase)
               || Regex.IsMatch(value, @"^\s*model\.", RegexOptions.IgnoreCase)
               || Regex.IsMatch(value, @"^\s*[A-Za-z_][\w.]*\(", RegexOptions.IgnoreCase));

    private static string ResolveExpr(BindingDesign? binding, bool inDetail, BindingMap map)
    {
        if (binding == null)
            return "\"\"";
        if (!string.IsNullOrWhiteSpace(binding.Expr))
        {
            if (Regex.IsMatch(binding.Expr!, @"^\s*ValorEnLetras\s*\("))
                return "LetterAmount(model)";
            return binding.Expr!;
        }
        return map.Resolve(binding.Xpath, inDetail, binding.Default);
    }

    /* ── Utilidades ────────────────────────────────────────── */

    private static string F(float value) => value.ToString("0.###", CultureInfo.InvariantCulture);

    private static string Escape(string? value)
        => (value ?? string.Empty).Replace("\\", "\\\\").Replace("\"", "\\\"").Replace("\r", "").Replace("\n", " ");

    private static string Sanitize(string name)
    {
        var sb = new StringBuilder();
        foreach (var ch in name)
            sb.Append(char.IsLetterOrDigit(ch) ? ch : '_');
        var result = sb.ToString().Trim('_');
        if (string.IsNullOrEmpty(result)) result = "Report";
        if (char.IsDigit(result[0])) result = "T" + result;
        return result;
    }

    /* ── Helpers autocontenidos emitidos en el template ────── */

    private const string CommonHelpers = """
        // ── Helpers ─────────────────────────────────────────────
        private static void RegisterEncodingProvider()
        {
            if (_encodingProviderRegistered) return;
            lock (_lock)
            {
                if (_encodingProviderRegistered) return;
                try
                {
                    Encoding.RegisterProvider(CodePagesEncodingProvider.Instance);
                    _encodingProviderRegistered = true;
                }
                catch
                {
                    _encodingProviderRegistered = false;
                }
            }
        }

        private static string GetCustomField(InvoiceModel model, string key, string defaultValue = "")
            => model.Additional?.CustomFields?.TryGetValue(key, out var value) == true && !string.IsNullOrEmpty(value)
                ? value
                : defaultValue;

        private static string LetterAmount(InvoiceModel model)
        {
            var letters = PDF_Utils.NumeroALetrasCOP(model.Document?.Total_am ?? 0m);
            return string.IsNullOrWhiteSpace(letters)
                ? model.Document?.TotalLetras ?? string.Empty
                : letters;
        }

        private static string Format(object? value, string? format)
        {
            if (value == null) return string.Empty;
            var text = value switch
            {
                DateTime dt => dt.ToString("dd/MM/yyyy", CultureInfo.InvariantCulture),
                decimal dec => dec.ToString(CultureInfo.InvariantCulture),
                double dbl => dbl.ToString(CultureInfo.InvariantCulture),
                IFormattable f => f.ToString(null, CultureInfo.InvariantCulture),
                _ => value.ToString() ?? string.Empty
            };
            if (string.IsNullOrWhiteSpace(format) || format == "text") return text;

            var culture = CultureInfo.GetCultureInfo("es-CO");
            if (format.StartsWith("date:", StringComparison.OrdinalIgnoreCase))
            {
                return DateTime.TryParse(text, CultureInfo.InvariantCulture, DateTimeStyles.None, out var date)
                    ? date.ToString(format[5..], culture)
                    : text;
            }

            decimal? num = decimal.TryParse(text.Replace("$", "").Replace(",", "").Trim(), NumberStyles.Any, CultureInfo.InvariantCulture, out var n)
                ? n : null;

            return format switch
            {
                "currency" => num?.ToString("C0", culture) ?? text,
                "currency2" => num?.ToString("C2", culture) ?? text,
                "number" => num?.ToString("N0", culture) ?? text,
                "number2" => num?.ToString("N2", culture) ?? text,
                "upper" => text.ToUpperInvariant(),
                "lower" => text.ToLowerInvariant(),
                _ => text
            };
        }

        private static byte[]? SafeLoadImage(string? source)
        {
            if (string.IsNullOrWhiteSpace(source)) return null;
            try
            {
                if (source.StartsWith("data:", StringComparison.OrdinalIgnoreCase))
                {
                    var idx = source.IndexOf("base64,", StringComparison.OrdinalIgnoreCase);
                    if (idx >= 0) return Convert.FromBase64String(source[(idx + 7)..]);
                }
                if (File.Exists(source)) return File.ReadAllBytes(source);
                return Convert.FromBase64String(source);
            }
            catch
            {
                return null;
            }
        }
        """;

    private const string LocalQrHelpers = """
        private static byte[]? SafeGenerateQRCode(string qrUrl)
        {
            if (string.IsNullOrWhiteSpace(qrUrl))
                return null;

            try
            {
                using var qrGenerator = new QRCodeGenerator();
                using var qrCodeData = qrGenerator.CreateQrCode(qrUrl, QRCodeGenerator.ECCLevel.L);
                using var qrCode = new PngByteQRCode(qrCodeData);
                return qrCode.GetGraphic(8);
            }
            catch (Exception)
            {
                return null;
            }
        }

        private static void DrawBarcode(IContainer cell, string? value, string symbology, float height)
        {
            if (string.IsNullOrWhiteSpace(value))
            {
                cell.Text("");
                return;
            }

            var isQr = string.Equals(symbology, "QR", StringComparison.OrdinalIgnoreCase)
                       || string.Equals(symbology, "QRCODE", StringComparison.OrdinalIgnoreCase);
            if (!isQr)
            {
                // El preview renderiza 1D vía ZXing; en el template generado se muestra como texto.
                cell.Text(value).FontSize(Math.Max(height - 4, 7f));
                return;
            }

            var bytes = SafeGenerateQRCode(value);
            if (bytes == null)
            {
                cell.Text("");
                return;
            }

            cell.Image(bytes).FitArea();
        }
        """;
}
